server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG                           # Логирование всех SQL-запросов
        type.descriptor.sql.BasicBinder: TRACE # Логирование привязанных параметров
        transaction: DEBUG                    # Логирование транзакций Hibernate
        engine: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testTest
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Отключаем автоматическое создание таблиц через Hibernate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml  # Файл с миграциями

indexing-settings:
  userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
  referrer: "http://www.google.com"
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
